[18:10:30] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/27 06:10:37: before drop huge graphs, there are 4110 graphs in NCI1
2022/03/27 06:10:37: after drop huge graphs, there are 4110 graphs in NCI1
2022/03/27 06:10:37: ready to generate node embeddings
/public1/home/scfa1517/HKS-Wasserstein-kernel/signature.py:101: ComplexWarning: Casting complex values to real discards the imaginary part
  wks[i] = np.array([np.sum(np.exp(-(e-log_eigenvalue)*(e-log_eigenvalue)/(2*sigma*sigma))*eigenvectors[i]*eigenvectors[i])/np.sum(np.exp(-(e-log_eigenvalue)*(e-log_eigenvalue)/(2*sigma*sigma))) for e in sample_points])
2022/03/27 06:46:24: the node embedding have been generated
2022/03/27 06:46:24: ready to compute the wass diss with sinkhorn = False and w = 0.4
2022/03/27 07:48:29: have computed the wass diss with sinkhorn = False and w = 0.4
[19:48:47] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/27 07:48:59: before drop huge graphs, there are 4110 graphs in NCI1
2022/03/27 07:48:59: after drop huge graphs, there are 4110 graphs in NCI1
2022/03/27 07:48:59: ready to generate node embeddings
/public1/home/scfa1517/HKS-Wasserstein-kernel/signature.py:101: ComplexWarning: Casting complex values to real discards the imaginary part
  wks[i] = np.array([np.sum(np.exp(-(e-log_eigenvalue)*(e-log_eigenvalue)/(2*sigma*sigma))*eigenvectors[i]*eigenvectors[i])/np.sum(np.exp(-(e-log_eigenvalue)*(e-log_eigenvalue)/(2*sigma*sigma))) for e in sample_points])
slurmstepd: error: *** JOB 1120099 ON ia0406 CANCELLED AT 2022-03-27T19:54:17 ***
