2022/04/01 11:43:31: loading the MUTAG dataset
2022/04/01 11:43:32: before drop huge graphs, there are 188 graphs in MUTAG
2022/04/01 11:43:32: after drop huge graphs, there are 188 graphs in MUTAG
2022/04/01 11:43:32: read to conduct SP kernel on MUTAG
2022/04/01 11:43:32: with gridserach = True and crossvalidation = True
2022/04/01 11:43:33: have conducted SP kernel on MUTAG
2022/04/01 11:43:33: read to conduct <class 'grakel.kernels.weisfeiler_lehman.WeisfeilerLehman'> on MUTAG
2022/04/01 11:43:33: with gridserach = True and crossvalidation = True
2022/04/01 11:43:33: have conducted <class 'grakel.kernels.weisfeiler_lehman.WeisfeilerLehman'> on MUTAG
2022/04/01 11:43:33: read to conduct <class 'grakel.kernels.graphlet_sampling.GraphletSampling'> on MUTAG
2022/04/01 11:43:33: with gridserach = True and crossvalidation = True
2022/04/01 11:43:34: have conducted <class 'grakel.kernels.graphlet_sampling.GraphletSampling'> on MUTAG
2022/04/01 11:43:34: read to conduct <class 'grakel.kernels.graphlet_sampling.GraphletSampling'> on MUTAG
2022/04/01 11:43:34: with gridserach = True and crossvalidation = True
2022/04/01 11:43:36: have conducted <class 'grakel.kernels.graphlet_sampling.GraphletSampling'> on MUTAG
2022/04/01 11:43:36: read to conduct <class 'grakel.kernels.random_walk.RandomWalkLabeled'> on MUTAG
2022/04/01 11:43:36: with gridserach = True and crossvalidation = True
2022/04/01 11:44:06: have conducted <class 'grakel.kernels.random_walk.RandomWalkLabeled'> on MUTAG
2022/04/01 11:44:07: loading the PTC_MR dataset
2022/04/01 11:44:08: before drop huge graphs, there are 344 graphs in PTC_MR
2022/04/01 11:44:08: after drop huge graphs, there are 340 graphs in PTC_MR
2022/04/01 11:44:08: read to conduct SP kernel on PTC_MR
2022/04/01 11:44:08: with gridserach = True and crossvalidation = True
2022/04/01 11:44:11: have conducted SP kernel on PTC_MR
2022/04/01 11:44:11: read to conduct <class 'grakel.kernels.weisfeiler_lehman.WeisfeilerLehman'> on PTC_MR
2022/04/01 11:44:11: with gridserach = True and crossvalidation = True
2022/04/01 11:44:12: have conducted <class 'grakel.kernels.weisfeiler_lehman.WeisfeilerLehman'> on PTC_MR
2022/04/01 11:44:12: read to conduct <class 'grakel.kernels.graphlet_sampling.GraphletSampling'> on PTC_MR
2022/04/01 11:44:12: with gridserach = True and crossvalidation = True
2022/04/01 11:44:13: have conducted <class 'grakel.kernels.graphlet_sampling.GraphletSampling'> on PTC_MR
2022/04/01 11:44:13: read to conduct <class 'grakel.kernels.graphlet_sampling.GraphletSampling'> on PTC_MR
2022/04/01 11:44:13: with gridserach = True and crossvalidation = True
2022/04/01 11:44:15: have conducted <class 'grakel.kernels.graphlet_sampling.GraphletSampling'> on PTC_MR
2022/04/01 11:44:15: read to conduct <class 'grakel.kernels.random_walk.RandomWalkLabeled'> on PTC_MR
2022/04/01 11:44:15: with gridserach = True and crossvalidation = True
2022/04/01 11:45:17: have conducted <class 'grakel.kernels.random_walk.RandomWalkLabeled'> on PTC_MR
2022/04/01 11:45:18: loading the PROTEINS dataset
2022/04/01 11:45:19: before drop huge graphs, there are 1113 graphs in PROTEINS
2022/04/01 11:45:19: after drop huge graphs, there are 1112 graphs in PROTEINS
2022/04/01 11:45:19: read to conduct SP kernel on PROTEINS
2022/04/01 11:45:19: with gridserach = True and crossvalidation = True
2022/04/01 11:45:55: have conducted SP kernel on PROTEINS
2022/04/01 11:45:55: read to conduct <class 'grakel.kernels.weisfeiler_lehman.WeisfeilerLehman'> on PROTEINS
2022/04/01 11:45:55: with gridserach = True and crossvalidation = True
2022/04/01 11:46:01: have conducted <class 'grakel.kernels.weisfeiler_lehman.WeisfeilerLehman'> on PROTEINS
2022/04/01 11:46:01: read to conduct <class 'grakel.kernels.graphlet_sampling.GraphletSampling'> on PROTEINS
2022/04/01 11:46:01: with gridserach = True and crossvalidation = True
2022/04/01 11:46:23: have conducted <class 'grakel.kernels.graphlet_sampling.GraphletSampling'> on PROTEINS
2022/04/01 11:46:23: read to conduct <class 'grakel.kernels.graphlet_sampling.GraphletSampling'> on PROTEINS
2022/04/01 11:46:23: with gridserach = True and crossvalidation = True
2022/04/01 11:47:23: have conducted <class 'grakel.kernels.graphlet_sampling.GraphletSampling'> on PROTEINS
2022/04/01 11:47:23: read to conduct <class 'grakel.kernels.random_walk.RandomWalkLabeled'> on PROTEINS
2022/04/01 11:47:23: with gridserach = True and crossvalidation = True
/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/grakel/kernels/kernel.py:201: RuntimeWarning: invalid value encountered in sqrt
  return km / np.sqrt(np.outer(self._X_diag, self._X_diag))
Traceback (most recent call last):
  File "/public1/home/scfa1517/HKS-Wasserstein-kernel/baselines/baselines.py", line 130, in <module>
    main()
  File "/public1/home/scfa1517/HKS-Wasserstein-kernel/baselines/baselines.py", line 111, in main
    gs, best_params,unit_result,param = utilities.custom_grid_search_cv(SVC(kernel='precomputed'), 
  File "/public1/home/scfa1517/HKS-Wasserstein-kernel/baselines/../utilities.py", line 40, in custom_grid_search_cv
    return ret_model.fit(precomputed_kernels[params[best_idx]['K_idx']], y), params[best_idx],fin_results,params
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 190, in fit
    X, y = self._validate_data(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/base.py", line 581, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 964, in check_X_y
    X = check_array(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
2022/04/01 12:22:52: loading the DD dataset
2022/04/01 12:22:55: before drop huge graphs, there are 1178 graphs in DD
2022/04/01 12:22:55: after drop huge graphs, there are 1126 graphs in DD
2022/04/01 12:22:55: read to conduct SP kernel on DD
2022/04/01 12:22:55: with gridserach = True and crossvalidation = True
2022/04/01 12:31:27: have conducted SP kernel on DD
2022/04/01 12:31:27: read to conduct <class 'grakel.kernels.weisfeiler_lehman.WeisfeilerLehman'> on DD
2022/04/01 12:31:27: with gridserach = True and crossvalidation = True
2022/04/01 12:31:40: have conducted <class 'grakel.kernels.weisfeiler_lehman.WeisfeilerLehman'> on DD
2022/04/01 12:31:40: read to conduct <class 'grakel.kernels.graphlet_sampling.GraphletSampling'> on DD
2022/04/01 12:31:40: with gridserach = True and crossvalidation = True
2022/04/01 12:35:59: have conducted <class 'grakel.kernels.graphlet_sampling.GraphletSampling'> on DD
2022/04/01 12:35:59: read to conduct <class 'grakel.kernels.graphlet_sampling.GraphletSampling'> on DD
2022/04/01 12:35:59: with gridserach = True and crossvalidation = True
2022/04/01 12:53:09: have conducted <class 'grakel.kernels.graphlet_sampling.GraphletSampling'> on DD
2022/04/01 12:53:09: read to conduct <class 'grakel.kernels.random_walk.RandomWalkLabeled'> on DD
2022/04/01 12:53:09: with gridserach = True and crossvalidation = True
/var/spool/slurm/d/job1128796/slurm_script: line 16: 228846 Killed                  python3 baselines.py -d DD -gs
2022/04/01 12:56:39: loading the ENZYMES dataset
2022/04/01 12:56:39: before drop huge graphs, there are 600 graphs in ENZYMES
2022/04/01 12:56:39: after drop huge graphs, there are 598 graphs in ENZYMES
2022/04/01 12:56:39: read to conduct SP kernel on ENZYMES
2022/04/01 12:56:39: with gridserach = True and crossvalidation = True
2022/04/01 12:56:54: have conducted SP kernel on ENZYMES
2022/04/01 12:56:54: read to conduct <class 'grakel.kernels.weisfeiler_lehman.WeisfeilerLehman'> on ENZYMES
2022/04/01 12:56:54: with gridserach = True and crossvalidation = True
2022/04/01 12:56:57: have conducted <class 'grakel.kernels.weisfeiler_lehman.WeisfeilerLehman'> on ENZYMES
2022/04/01 12:56:57: read to conduct <class 'grakel.kernels.graphlet_sampling.GraphletSampling'> on ENZYMES
2022/04/01 12:56:57: with gridserach = True and crossvalidation = True
2022/04/01 12:57:07: have conducted <class 'grakel.kernels.graphlet_sampling.GraphletSampling'> on ENZYMES
2022/04/01 12:57:07: read to conduct <class 'grakel.kernels.graphlet_sampling.GraphletSampling'> on ENZYMES
2022/04/01 12:57:07: with gridserach = True and crossvalidation = True
/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/grakel/kernels/graphlet_sampling.py:324: RuntimeWarning: invalid value encountered in true_divide
  return np.divide(km, np.sqrt(np.outer(self._X_diag, self._X_diag)))
/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 761, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 216, in __call__
    return self._score(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 258, in _score
    y_pred = method_caller(estimator, "predict", X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 68, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 791, in predict
    y = super().predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 414, in predict
    X = self._validate_for_predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 592, in _validate_for_predict
    X = self._validate_data(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/base.py", line 566, in _validate_data
    X = check_array(X, **check_params)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

  warnings.warn(
/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 761, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 216, in __call__
    return self._score(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 258, in _score
    y_pred = method_caller(estimator, "predict", X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 68, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 791, in predict
    y = super().predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 414, in predict
    X = self._validate_for_predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 592, in _validate_for_predict
    X = self._validate_data(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/base.py", line 566, in _validate_data
    X = check_array(X, **check_params)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

  warnings.warn(
/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 761, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 216, in __call__
    return self._score(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 258, in _score
    y_pred = method_caller(estimator, "predict", X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 68, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 791, in predict
    y = super().predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 414, in predict
    X = self._validate_for_predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 592, in _validate_for_predict
    X = self._validate_data(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/base.py", line 566, in _validate_data
    X = check_array(X, **check_params)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

  warnings.warn(
/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 761, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 216, in __call__
    return self._score(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 258, in _score
    y_pred = method_caller(estimator, "predict", X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 68, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 791, in predict
    y = super().predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 414, in predict
    X = self._validate_for_predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 592, in _validate_for_predict
    X = self._validate_data(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/base.py", line 566, in _validate_data
    X = check_array(X, **check_params)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

  warnings.warn(
/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 761, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 216, in __call__
    return self._score(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 258, in _score
    y_pred = method_caller(estimator, "predict", X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 68, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 791, in predict
    y = super().predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 414, in predict
    X = self._validate_for_predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 592, in _validate_for_predict
    X = self._validate_data(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/base.py", line 566, in _validate_data
    X = check_array(X, **check_params)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

  warnings.warn(
/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 761, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 216, in __call__
    return self._score(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 258, in _score
    y_pred = method_caller(estimator, "predict", X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 68, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 791, in predict
    y = super().predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 414, in predict
    X = self._validate_for_predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 592, in _validate_for_predict
    X = self._validate_data(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/base.py", line 566, in _validate_data
    X = check_array(X, **check_params)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

  warnings.warn(
/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 761, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 216, in __call__
    return self._score(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 258, in _score
    y_pred = method_caller(estimator, "predict", X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 68, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 791, in predict
    y = super().predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 414, in predict
    X = self._validate_for_predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 592, in _validate_for_predict
    X = self._validate_data(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/base.py", line 566, in _validate_data
    X = check_array(X, **check_params)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

  warnings.warn(
Traceback (most recent call last):
  File "/public1/home/scfa1517/HKS-Wasserstein-kernel/baselines/baselines.py", line 130, in <module>
    main()
  File "/public1/home/scfa1517/HKS-Wasserstein-kernel/baselines/baselines.py", line 111, in main
    gs, best_params,unit_result,param = utilities.custom_grid_search_cv(SVC(kernel='precomputed'), 
  File "/public1/home/scfa1517/HKS-Wasserstein-kernel/baselines/../utilities.py", line 40, in custom_grid_search_cv
    return ret_model.fit(precomputed_kernels[params[best_idx]['K_idx']], y), params[best_idx],fin_results,params
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 190, in fit
    X, y = self._validate_data(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/base.py", line 581, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 964, in check_X_y
    X = check_array(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
